import { Children, cloneElement, isValidElement, useEffect, useId, useState, type FormEvent, type ReactElement, type ReactNode } from 'react';
import { X } from 'lucide-react';
import type { CalendarSystem, Goal, GoalInput, GoalRelation, MidTermGoalInput, RoutinePattern, ShortTermTask, ShortTermTaskInput } from '../../domain/models';
import { calendarParts, calendarYearEndKey, todayKey } from '../calendar/calendar';
import { CalendarDateField } from '../../components/CalendarDateField';
import { SelectField } from '../../components/SelectField';

type TaskType = 'long-term' | 'mid-term' | 'short-term';
type MidForm = Omit<MidTermGoalInput, 'kind' | 'title'>;
const weekdays = [{ name: 'شنبه', value: 6 }, { name: 'یکشنبه', value: 0 }, { name: 'دوشنبه', value: 1 }, { name: 'سه‌شنبه', value: 2 }, { name: 'چهارشنبه', value: 3 }, { name: 'پنجشنبه', value: 4 }, { name: 'جمعه', value: 5 }];
const categories = [['career', 'کار و حرفه'], ['education', 'آموزش و یادگیری'], ['money', 'مالی'], ['health', 'سلامت'], ['relationships', 'روابط'], ['growth', 'رشد فردی'], ['lifestyle', 'سبک زندگی'], ['creative', 'پروژه‌ی خلاقانه'], ['other', 'سایر']];
const colors = ['#718aa8', '#668f7b', '#b58a68', '#9280a7', '#7c9da2'];
function initialMidForm(): MidForm {
  return { relatedLongTermGoals: [], category: 'education', customCategory: '', why: '', importance: 5, deadlineChoice: 'unsure', dateReason: '', deadlineType: '', realism: 'unsure', doneCriteria: '', milestones: ['', '', '', '', ''], keyMilestone: 0, firstAction: '', weeklyHours: 3, tradeoffs: '', difficulty: 5, obstacles: ['', '', ''], controllableObstacle: 0, motivationPlan: '', priorityChoice: 'unsure', competingGoals: '', adaptPlan: '', progressMeasures: '', reviewFrequency: 'weekly', reviewFrequencyOther: '', progressOneMonth: '', progressThreeMonths: '', progressHalfway: '', checkWant: 'unsure', checkEffort: 'unsure', checkSpecific: 'yes', checkTimeframe: 'not-needed', checkInfluence: 'partly', checkFirstStep: 'no', finalWant: '', finalBecause: '', finalBy: '', finalSuccess: '', finalFirstStep: '', finalReviewDate: '' };
}
function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) {
  const labelId = useId();
  const labelledChildren = Children.map(children, child => {
    if (!isValidElement(child)) return child;
    if (child.type === SelectField || (typeof child.type === 'string' && ['input', 'select', 'textarea'].includes(child.type))) return cloneElement(child as ReactElement<Record<string, unknown>>, { 'aria-labelledby': labelId });
    if (child.type === TextArea) return cloneElement(child as ReactElement<{ ariaLabelledBy?: string }>, { ariaLabelledBy: labelId });
    return child;
  });
  return <div className="do-field"><span id={labelId}>{label}</span>{labelledChildren}{hint && <small>{hint}</small>}</div>;
}
function TextArea({ value, onChange, placeholder, ariaLabelledBy }: { value: string; onChange: (value: string) => void; placeholder?: string; ariaLabelledBy?: string }) { return <textarea aria-labelledby={ariaLabelledBy} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} rows={3}/>; }
function RelationPicker({ goals, values, onChange, emptyText }: { goals: Goal[]; values: GoalRelation[]; onChange: (values: GoalRelation[]) => void; emptyText: string }) {
  if (!goals.length) return <p className="do-empty-help">{emptyText}</p>;
  function toggle(goalId: string) { const current = values.find(item => item.goalId === goalId); onChange(current ? values.filter(item => item.goalId !== goalId) : [...values, { goalId, coefficient: 3 }]); }
  function coefficient(goalId: string, value: number) { onChange(values.map(item => item.goalId === goalId ? { ...item, coefficient: value as GoalRelation['coefficient'] } : item)); }
  return <div className="relation-list">{goals.map(goal => { const relation = values.find(item => item.goalId === goal.id); return <div className={`relation-row ${relation ? 'selected' : ''}`} key={goal.id}><label><input type="checkbox" checked={Boolean(relation)} onChange={() => toggle(goal.id)}/><span>{goal.title}</span></label>{relation && <label className="coefficient-field"><small>ضریب اثر</small><SelectField aria-label={`ضریب اثر برای ${goal.title}`} value={relation.coefficient} onValueChange={value => coefficient(goal.id, Number(value))}>{[1, 2, 3, 4, 5].map(value => <option key={value} value={value}>{value}</option>)}</SelectField></label>}</div>; })}</div>;
}

export function DoTaskDialog({ open, calendar, goals, editing, onClose, onSaveGoal, onSaveShortTask, onUpdateGoal, onUpdateShortTask }: {
  open: boolean; calendar: CalendarSystem; goals: Goal[]; onClose: () => void;
  editing?: Goal | ShortTermTask;
  onSaveGoal: (goal: GoalInput) => Promise<void>; onSaveShortTask: (task: ShortTermTaskInput) => Promise<void>;
  onUpdateGoal: (id: string, goal: GoalInput) => Promise<void>; onUpdateShortTask: (id: string, task: ShortTermTaskInput) => Promise<void>;
}) {
  const [type, setType] = useState<TaskType>('short-term');
  const [goalTitle, setGoalTitle] = useState(''); const [longYear, setLongYear] = useState(calendarParts(todayKey(), calendar).year + 1); const [longNote, setLongNote] = useState('');
  const [mid, setMid] = useState<MidForm>(initialMidForm); const [midTitle, setMidTitle] = useState('');
  const [shortMode, setShortMode] = useState<'job' | 'routine'>('job'); const [shortTitle, setShortTitle] = useState('');
  const [jobDate, setJobDate] = useState(''); const [jobTime, setJobTime] = useState(''); const [priority, setPriority] = useState(5); const [shortRelations, setShortRelations] = useState<GoalRelation[]>([]);
  const [pattern, setPattern] = useState<RoutinePattern>('daily'); const [routineDays, setRoutineDays] = useState<number[]>([6, 0, 1, 2, 3, 4, 5]);
  const [routineStart, setRoutineStart] = useState(todayKey()); const [routineEnd, setRoutineEnd] = useState(''); const [infinite, setInfinite] = useState(true);
  const [isTimed, setIsTimed] = useState(false); const [startTime, setStartTime] = useState('09:00'); const [endTime, setEndTime] = useState('10:00');
  const [color, setColor] = useState(colors[0]); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const midGoals = goals.filter((goal): goal is Extract<Goal, { kind: 'mid-term' }> => goal.kind === 'mid-term');
  const longGoals = goals.filter((goal): goal is Extract<Goal, { kind: 'long-term' }> => goal.kind === 'long-term');
  const currentYear = calendarParts(todayKey(), calendar).year;

  useEffect(() => { if (!open) return; setError(''); setType('short-term'); setGoalTitle(''); setLongYear(currentYear + 1); setLongNote(''); setMid(initialMidForm()); setMidTitle(''); setShortMode('job'); setShortTitle(''); setJobDate(''); setJobTime(''); setPriority(5); setShortRelations([]); setPattern('daily'); setRoutineDays([6, 0, 1, 2, 3, 4, 5]); setRoutineStart(todayKey()); setRoutineEnd(''); setInfinite(true); setIsTimed(false); setStartTime('09:00'); setEndTime('10:00'); setColor(colors[0]);
    if (!editing) return;
    if (editing.kind === 'long-term') { setType('long-term'); setGoalTitle(editing.title); setLongYear(calendarParts(editing.deadlineDate, calendar).year); setLongNote(editing.note); }
    else if (editing.kind === 'mid-term') { const { id: _id, kind: _kind, title, createdAt: _createdAt, updatedAt: _updatedAt, ...form } = editing; setType('mid-term'); setMidTitle(title); setMid(form); }
    else { setType('short-term'); setShortMode(editing.mode); setShortTitle(editing.title); setPriority(editing.priority); setColor(editing.color); setShortRelations(editing.relatedMidTermGoals); setJobDate(editing.triggerDate ?? ''); setJobTime(editing.triggerTime ?? ''); if (editing.routine) { setPattern(editing.routine.pattern); setRoutineDays(editing.routine.weekdays); setRoutineStart(editing.routine.startDate); setRoutineEnd(editing.routine.endDate ?? ''); setInfinite(!editing.routine.endDate); setIsTimed(editing.routine.isTimed); setStartTime(editing.routine.startTime ?? '09:00'); setEndTime(editing.routine.endTime ?? '10:00'); } }
  }, [open, currentYear, editing, calendar]);
  function changeMid<K extends keyof MidForm>(key: K, value: MidForm[K]) { setMid(current => ({ ...current, [key]: value })); }
  function toggleRoutineDay(day: number) { setRoutineDays(days => days.includes(day) ? days.filter(value => value !== day) : [...days, day]); }
  async function submit(event: FormEvent) {
    event.preventDefault(); setError('');
    if (type === 'long-term' && !goalTitle.trim()) { setError('عنوان هدف را وارد کنید.'); return; }
    if (type === 'mid-term' && !midTitle.trim()) { setError('عنوان هدف را وارد کنید.'); return; }
    if (type === 'mid-term' && mid.deadlineChoice === 'yes' && !mid.deadlineDate) { setError('برای هدف دارای مهلت، تاریخ را انتخاب کنید.'); return; }
    if (type === 'mid-term' && mid.milestones.filter(item => item.trim()).length < 3) { setError('برای مسیر هدف دست‌کم سه مرحله بنویسید.'); return; }
    if (type === 'short-term' && !shortTitle.trim()) { setError('عنوان کار را وارد کنید.'); return; }
    if (type === 'short-term' && shortMode === 'routine' && pattern === 'selected' && !routineDays.length) { setError('روزهای تکرار را انتخاب کنید.'); return; }
    if (type === 'short-term' && shortMode === 'routine' && routineEnd && routineEnd < routineStart) { setError('تاریخ پایان باید بعد از شروع باشد.'); return; }
    if (type === 'short-term' && shortMode === 'routine' && isTimed && (!startTime || !endTime || endTime === startTime)) { setError('ساعت شروع و پایان را وارد کنید؛ این دو ساعت نباید یکسان باشند.'); return; }
    setSaving(true);
    try {
      if (type === 'long-term') {
        const input: GoalInput = { kind: 'long-term', title: goalTitle.trim(), deadlineDate: calendarYearEndKey(longYear, calendar), note: longNote.trim() };
        if (editing?.kind === 'long-term') await onUpdateGoal(editing.id, input); else await onSaveGoal(input);
      } else if (type === 'mid-term') {
        const input: GoalInput = { ...mid, kind: 'mid-term', title: midTitle.trim(), milestones: mid.milestones.map(item => item.trim()).filter(Boolean), obstacles: mid.obstacles.map(item => item.trim()).filter(Boolean), keyMilestone: Math.max(0, Math.min(mid.keyMilestone, mid.milestones.filter(item => item.trim()).length - 1)), controllableObstacle: Math.max(0, Math.min(mid.controllableObstacle, mid.obstacles.filter(item => item.trim()).length - 1)) };
        if (editing?.kind === 'mid-term') await onUpdateGoal(editing.id, input); else await onSaveGoal(input);
      } else {
        const input: ShortTermTaskInput = { kind: 'short-term', mode: shortMode, title: shortTitle.trim(), color, priority, relatedMidTermGoals: shortRelations, triggerDate: shortMode === 'job' ? jobDate || undefined : undefined, triggerTime: shortMode === 'job' ? jobTime || undefined : undefined, routine: shortMode === 'routine' ? { pattern, weekdays: pattern === 'selected' ? routineDays : [], startDate: routineStart, endDate: infinite ? undefined : routineEnd || undefined, isTimed, startTime: isTimed ? startTime : undefined, endTime: isTimed ? endTime : undefined } : undefined, completed: editing?.kind === 'short-term' && editing.mode === shortMode ? editing.completed : false, completedDates: editing?.kind === 'short-term' && editing.mode === shortMode ? editing.completedDates : [] };
        if (editing?.kind === 'short-term') await onUpdateShortTask(editing.id, input); else await onSaveShortTask(input);
      }
      onClose();
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'ذخیره‌ی کار انجام نشد.'); }
    finally { setSaving(false); }
  }

  if (!open) return null;
  const yearOptions = Array.from({ length: 46 }, (_, index) => currentYear - 30 + index);
  const relatedMidPicker = <RelationPicker goals={midGoals} values={shortRelations} onChange={setShortRelations} emptyText="برای پیوند دادن کار، ابتدا یک هدف میان‌مدت بسازید."/>;
  const relatedLongPicker = <RelationPicker goals={longGoals} values={mid.relatedLongTermGoals} onChange={value => changeMid('relatedLongTermGoals', value)} emptyText="هنوز هدف بلندمدتی نساخته‌اید؛ این پیوند اختیاری است."/>;
  return <div className="modal-backdrop do-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><form className="do-dialog" onSubmit={submit} aria-labelledby="do-title">
    <header className="do-header"><div><span className="do-kicker">{editing ? 'ویرایش مورد انتخاب‌شده' : 'طراحی هدف و اقدام'}</span><h2 id="do-title">{editing ? 'جزئیات را به‌روز کن.' : 'برای چیزی که می‌خواهی، قدم بردار.'}</h2></div><button className="icon-button" type="button" aria-label="بستن" onClick={onClose}><X size={18}/></button></header>
    {!editing && <div className="do-type-switch" role="tablist" aria-label="نوع کار">{([['long-term', 'بلندمدت'], ['mid-term', 'میان‌مدت'], ['short-term', 'کوتاه‌مدت']] as const).map(([value, label], index) => <button type="button" role="tab" aria-selected={type === value} className={type === value ? 'active' : ''} key={value} onClick={() => { setType(value); setError(''); }}><small>{new Intl.NumberFormat('fa-IR', { minimumIntegerDigits: 2 }).format(index + 1)}</small>{label}</button>)}</div>}
    <div className="do-form-scroll">
      {type === 'long-term' && <div className="do-form-content"><p className="do-intro">یک مقصد سالانه انتخاب کن؛ لازم نیست مسیرش را همین حالا بدانی.</p><Field label="عنوان هدف"><input autoFocus required value={goalTitle} onChange={event => setGoalTitle(event.target.value)} placeholder="مثلاً ساختن کسب‌وکار شخصی"/></Field><Field label="سال هدف"><SelectField value={longYear} onValueChange={value => setLongYear(Number(value))}>{yearOptions.map(year => <option key={year} value={year}>{new Intl.NumberFormat(calendar === 'persian' ? 'fa-IR-u-ca-persian' : 'en').format(year)}</option>)}</SelectField></Field><Field label="یادداشت"><TextArea value={longNote} onChange={setLongNote} placeholder="چرا این مقصد برایت مهم است؟ هر نکته‌ای را اینجا بنویس…"/></Field></div>}

      {type === 'mid-term' && <div className="do-form-content mid-form">
        <details open><summary>۱. خود هدف</summary><div className="details-content"><Field label="عنوان هدف"><input autoFocus required value={midTitle} onChange={event => setMidTitle(event.target.value)} placeholder="می‌خواهم به چه چیزی برسم؟"/></Field><Field label="این هدف در کدام حوزه است؟"><div className="choice-grid category-grid">{categories.map(([value, label]) => <label key={value} className={mid.category === value ? 'selected' : ''}><input type="radio" name="goal-category" checked={mid.category === value} onChange={() => changeMid('category', value)}/>{label}</label>)}</div></Field>{mid.category === 'other' && <Field label="حوزه‌ی دیگر"><input value={mid.customCategory} onChange={event => changeMid('customCategory', event.target.value)}/></Field>}<Field label="چرا این هدف را می‌خواهی؟"><TextArea value={mid.why} onChange={value => changeMid('why', value)}/></Field><Field label={`اهمیت برای من · ${mid.importance} از ۱۰`}><input type="range" min="1" max="10" value={mid.importance} onChange={event => changeMid('importance', Number(event.target.value))}/></Field></div></details>
        <details><summary>۲. بازه‌ی زمانی</summary><div className="details-content"><Field label="مهلت می‌خواهی؟"><SelectField value={mid.deadlineChoice} onValueChange={value => changeMid('deadlineChoice', value as MidForm['deadlineChoice'])}><option value="yes">بله</option><option value="no">خیر</option><option value="unsure">هنوز مطمئن نیستم</option></SelectField></Field>{mid.deadlineChoice === 'yes' && <><Field label="تا چه تاریخی؟"><CalendarDateField value={mid.deadlineDate ?? ''} calendar={calendar} onChange={value => changeMid('deadlineDate', value || undefined)}/></Field><Field label="چرا این تاریخ؟"><TextArea value={mid.dateReason} onChange={value => changeMid('dateReason', value)}/></Field><Field label="این مهلت چه نوعی است؟"><SelectField value={mid.deadlineType} onValueChange={value => changeMid('deadlineType', value as MidForm['deadlineType'])}><option value="">انتخاب کنید</option><option value="fixed">قطعی و بیرونی</option><option value="self-imposed">انتخاب خودم</option><option value="flexible">انعطاف‌پذیر</option></SelectField></Field></>}<Field label="واقع‌بینانه بودن بازه"><SelectField value={mid.realism} onValueChange={value => changeMid('realism', value as MidForm['realism'])}><option value="definitely">قطعاً</option><option value="probably">احتمالاً</option><option value="unsure">مطمئن نیستم</option><option value="probably-not">احتمالاً نه</option></SelectField></Field></div></details>
        <details><summary>۳. تعریف موفقیت و مسیر</summary><div className="details-content"><Field label="چه چیزی باید درست باشد تا بگویی به هدف رسیده‌ای؟"><TextArea value={mid.doneCriteria} onChange={value => changeMid('doneCriteria', value)}/></Field><Field label="سه تا پنج اتفاق مهم برای رسیدن به هدف"><div className="stacked-fields">{mid.milestones.map((value, index) => <input key={index} value={value} onChange={event => changeMid('milestones', mid.milestones.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} placeholder={`مرحله‌ی ${index + 1}${index > 2 ? ' (اختیاری)' : ''}`}/>)}</div></Field><Field label="مهم‌ترین مرحله"><SelectField value={mid.keyMilestone} onValueChange={value => changeMid('keyMilestone', Number(value))}>{mid.milestones.map((value, index) => <option key={index} value={index}>{value.trim() || `مرحله‌ی ${index + 1}`}</option>)}</SelectField></Field><Field label="اولین اقدام مشخص"><TextArea value={mid.firstAction} onChange={value => changeMid('firstAction', value)}/></Field></div></details>
        <details><summary>۴. تعهد و موانع</summary><div className="details-content"><Field label={`زمان واقع‌بینانه در هفته · ${mid.weeklyHours} ساعت`}><input type="number" min="0" max="168" value={mid.weeklyHours} onChange={event => changeMid('weeklyHours', Number(event.target.value))}/></Field><Field label="برای این هدف چه چیزی را کم می‌کنی یا کنار می‌گذاری؟"><TextArea value={mid.tradeoffs} onChange={value => changeMid('tradeoffs', value)}/></Field><Field label={`سختی مورد انتظار · ${mid.difficulty} از ۱۰`}><input type="range" min="1" max="10" value={mid.difficulty} onChange={event => changeMid('difficulty', Number(event.target.value))}/></Field><Field label="سه مانع احتمالی"><div className="stacked-fields">{mid.obstacles.map((value, index) => <input key={index} value={value} onChange={event => changeMid('obstacles', mid.obstacles.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} placeholder={`مانع ${index + 1}`}/>)}</div></Field><Field label="کدام مانع در کنترل توست؟"><SelectField value={mid.controllableObstacle} onValueChange={value => changeMid('controllableObstacle', Number(value))}>{mid.obstacles.map((value, index) => <option key={index} value={index}>{value.trim() || `مانع ${index + 1}`}</option>)}</SelectField></Field><Field label="اگر انگیزه‌ات کم شد یا عقب افتادی، چه می‌کنی؟"><TextArea value={mid.motivationPlan} onChange={value => changeMid('motivationPlan', value)}/></Field></div></details>
        <details><summary>۵. اولویت‌ها و سنجش پیشرفت</summary><div className="details-content"><Field label="اگر فقط یک کار در ۶ تا ۱۲ ماه آینده انجام دهی، همین هدف است؟"><SelectField value={mid.priorityChoice} onValueChange={value => changeMid('priorityChoice', value as MidForm['priorityChoice'])}><option value="yes">بله</option><option value="no">خیر</option><option value="unsure">مطمئن نیستم</option></SelectField></Field><Field label="چه هدف‌هایی با آن رقابت می‌کنند؟"><TextArea value={mid.competingGoals} onChange={value => changeMid('competingGoals', value)}/></Field><Field label="اگر چیزی مهم‌تر شد، چه چیزی را تغییر می‌دهی؟"><TextArea value={mid.adaptPlan} onChange={value => changeMid('adaptPlan', value)}/></Field><Field label="برای سنجش پیشرفت چه چیزی را اندازه می‌گیری؟"><TextArea value={mid.progressMeasures} onChange={value => changeMid('progressMeasures', value)}/></Field><Field label="هر چند وقت یک‌بار بازبینی می‌کنی؟"><SelectField value={mid.reviewFrequency} onValueChange={value => changeMid('reviewFrequency', value as MidForm['reviewFrequency'])}><option value="weekly">هر هفته</option><option value="two-weeks">هر دو هفته</option><option value="monthly">هر ماه</option><option value="other">بازه‌ی دیگر</option></SelectField></Field>{mid.reviewFrequency === 'other' && <Field label="بازه‌ی بازبینی"><input value={mid.reviewFrequencyOther} onChange={event => changeMid('reviewFrequencyOther', event.target.value)}/></Field>}<Field label="پیشرفت خوب بعد از یک ماه"><TextArea value={mid.progressOneMonth} onChange={value => changeMid('progressOneMonth', value)}/></Field><Field label="بعد از سه ماه"><TextArea value={mid.progressThreeMonths} onChange={value => changeMid('progressThreeMonths', value)}/></Field><Field label="در نیمه‌ی مسیر"><TextArea value={mid.progressHalfway} onChange={value => changeMid('progressHalfway', value)}/></Field></div></details>
        <details><summary>۶. بررسی نهایی و پیوندها</summary><div className="details-content"><div className="final-check-grid">{([['checkWant', 'واقعاً این هدف را می‌خواهم؟', ['yes', 'no', 'unsure']], ['checkEffort', 'ارزش این تلاش را دارد؟', ['yes', 'no', 'unsure']], ['checkSpecific', 'به‌اندازه‌ی کافی مشخص است؟', ['yes', 'no']], ['checkTimeframe', 'بازه روشن است؟', ['yes', 'no', 'not-needed']], ['checkInfluence', 'می‌توانم بر نتیجه اثر بگذارم؟', ['yes', 'partly', 'no']], ['checkFirstStep', 'اولین قدم را می‌دانم؟', ['yes', 'no']]] as const).map(([key, label, options]) => <Field key={key} label={label}><SelectField value={mid[key]} onValueChange={value => changeMid(key, value as never)}>{options.map(value => <option key={value} value={value}>{({ yes: 'بله', no: 'خیر', unsure: 'مطمئن نیستم', 'not-needed': 'لازم نیست', partly: 'تاحدی' } as Record<string, string>)[value]}</option>)}</SelectField></Field>)}</div><Field label="هدف نهایی من"><TextArea value={mid.finalWant} onChange={value => changeMid('finalWant', value)} placeholder="می‌خواهم…"/></Field><Field label="چون"><TextArea value={mid.finalBecause} onChange={value => changeMid('finalBecause', value)}/></Field><Field label="تا"><CalendarDateField value={mid.finalBy} calendar={calendar} onChange={value => changeMid('finalBy', value)}/></Field><Field label="وقتی می‌دانم رسیده‌ام که"><TextArea value={mid.finalSuccess} onChange={value => changeMid('finalSuccess', value)}/></Field><Field label="اولین قدمم"><TextArea value={mid.finalFirstStep} onChange={value => changeMid('finalFirstStep', value)}/></Field><Field label="تاریخ بازبینی"><CalendarDateField value={mid.finalReviewDate} calendar={calendar} onChange={value => changeMid('finalReviewDate', value)}/></Field><Field label="هدف‌های بلندمدت مرتبط (اختیاری)">{relatedLongPicker}</Field></div></details>
      </div>}

      {type === 'short-term' && <div className="do-form-content short-form"><p className="do-intro">یک اقدام مشخص بساز یا عادتی را برای تکرار برنامه‌ریزی کن.</p><div className="segmented short-kind"><button type="button" className={shortMode === 'job' ? 'active' : ''} onClick={() => setShortMode('job')}>کار مشخص</button><button type="button" className={shortMode === 'routine' ? 'active' : ''} onClick={() => setShortMode('routine')}>روتین</button></div><Field label="عنوان"><input autoFocus required value={shortTitle} onChange={event => setShortTitle(event.target.value)} placeholder={shortMode === 'job' ? 'مثلاً ارسال رزومه' : 'مثلاً تمرین زبان'}/></Field><Field label="هدف‌های میان‌مدت مرتبط (اختیاری)">{relatedMidPicker}</Field>{shortMode === 'job' ? <><Field label="تاریخ انجام (اختیاری)"><CalendarDateField value={jobDate} calendar={calendar} onChange={setJobDate}/></Field><Field label="ساعت (اختیاری)"><input type="time" value={jobTime} onChange={event => setJobTime(event.target.value)}/></Field><Field label={`اولویت · ${priority} از ۱۰`}><input type="range" min="1" max="10" value={priority} onChange={event => setPriority(Number(event.target.value))}/></Field></> : <>
        <Field label="این روتین چه وقت‌هایی تکرار شود؟"><SelectField value={pattern} onValueChange={value => setPattern(value as RoutinePattern)}><option value="daily">هر روز</option><option value="weekdays">روزهای کاری هفته</option><option value="weekends">آخر هفته</option><option value="selected">روزهای انتخابی هفته</option><option value="even-dates">روزهای زوج ماه</option><option value="odd-dates">روزهای فرد ماه</option></SelectField></Field>{pattern === 'selected' && <div className="weekday-picks">{weekdays.map(day => <button type="button" key={day.value} className={routineDays.includes(day.value) ? 'active' : ''} onClick={() => toggleRoutineDay(day.value)}>{day.name}</button>)}</div>}
        <div className="do-inline-fields"><Field label="شروع"><CalendarDateField value={routineStart} calendar={calendar} allowEmpty={false} onChange={setRoutineStart}/></Field><Field label="پایان (اختیاری)">{infinite ? <span className="date-disabled">بدون پایان</span> : <CalendarDateField value={routineEnd} calendar={calendar} onChange={setRoutineEnd}/>}</Field></div><label className="check-line"><input type="checkbox" checked={infinite} onChange={event => setInfinite(event.target.checked)}/> بدون تاریخ پایان؛ از حالا و برای همیشه</label><label className="check-line"><input type="checkbox" checked={isTimed} onChange={event => setIsTimed(event.target.checked)}/> این روتین بازه‌ی زمانی مشخص دارد</label>{isTimed && <div className="do-inline-fields"><Field label="از ساعت"><input type="time" value={startTime} onChange={event => setStartTime(event.target.value)}/></Field><Field label="تا ساعت" hint={startTime && endTime && endTime < startTime ? 'پایان این بازه در روز بعد است.' : undefined}><input type="time" value={endTime} onChange={event => setEndTime(event.target.value)}/></Field></div>}
        <Field label={`اولویت · ${priority} از ۱۰`}><input type="range" min="1" max="10" value={priority} onChange={event => setPriority(Number(event.target.value))}/></Field>
      </>}</div>}
    </div>
    {type === 'short-term' && <div className="do-color-row"><span>رنگ</span>{colors.map(value => <button key={value} type="button" aria-label="انتخاب رنگ" aria-pressed={color === value} onClick={() => setColor(value)} style={{ background: value }}/>)}</div>}
    {error && <p className="do-error" role="alert">{error}</p>}
    <footer className="do-footer"><button type="button" className="button secondary" onClick={onClose}>انصراف</button><button type="submit" className="button do-save" disabled={saving}>{saving ? 'در حال ذخیره…' : editing ? 'ذخیره‌ی تغییرات' : 'ذخیره در برنامه'}</button></footer>
  </form></div>;
}
